### PR TITLE
[ AMSD-110 ] Push the current version of client to main branch

### PR DESCRIPTION
**Pull request by floriansaqipi**
The develop branch of the client app has to be merged to the main branch.

### CODE REVIEW

**Review by ArianitSGashi — APPROVED** [review]
Good job!

**Review by ArdiZariqi — APPROVED** [review]
Nicely done!

**Review by Gentrit851 — APPROVED** [review]
Nicely done!

**Review by ArditGjyrevci — APPROVED** [review]
Nice job!

**Pull request merged**
